In [1]:
import pandas as pd
import numpy as np

In [23]:
inputvector=np.array([1,2,3,4,5])
inputvector

array([1, 2, 3, 4, 5])

# Alexandre-Theophile Vandermonde learning

In [8]:
#np.vander(inputvector,increasing=True)
np.vander(inputvector,increasing=False)

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [7]:
N=5
np.column_stack(inputvector**(N-1-i) for i in range(N))

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]], dtype=int32)

In [20]:
n=5
for x in inputvector:
    for i in range(n):
        pass
        #print(x**(n-i-1))

inputvalue=[x**(n-i-1) for x in inputvector for i in range(n)]
np.reshape(inputvalue,(inputvector.size,n))

array([[  1,   1,   1,   1,   1],
       [ 16,   8,   4,   2,   1],
       [ 81,  27,   9,   3,   1],
       [256,  64,  16,   4,   1],
       [625, 125,  25,   5,   1]])

In [35]:
def fun(x,n,flag):
    if not flag:
        inputvalue=[x**(n-i-1) for x in inputvector for i in range(n)]
    elif flag:
        inputvalue=[x**i for x in inputvector for i in range(n)]
    return inputvalue

d=fun(inputvector,5,True)
np.reshape(d,(inputvector.size,n))

array([[  1,   1,   1,   1,   1],
       [  1,   2,   4,   8,  16],
       [  1,   3,   9,  27,  81],
       [  1,   4,  16,  64, 256],
       [  1,   5,  25, 125, 625]])

# find moving average in an array over a window

In [81]:
mylist = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]

In [23]:
def fun_ave(mylist,n):
    sum_value, movingaverage = [0], []
    for i,x in enumerate(mylist,1):
        sum_value.append(sum_value[i-1] + x)
        if i>=n:
            movingaverage.append(round((sum_value[i]-sum_value[i-n])/n,2))
    return movingaverage


In [27]:
mylist = [3, 5, 7, 2, 8, 10, 11, 65, 72, 81, 99, 100, 150]
fun_ave(mylist,3)

[5.0, 4.67, 5.67, 6.67, 9.67, 28.67, 49.33, 72.67, 84.0, 93.33, 116.33]

In [29]:
mylist=[10, 20, 30, 40, 50, 60, 70, 80, 90, 100]
fun_ave(mylist,4)

[25.0, 35.0, 45.0, 55.0, 65.0, 75.0, 85.0]